// ─── KAI DART — Seed Station Data ────────────────────────────────────────────
// 3 strategic stations chosen for the demo: Mockingbird, Downtown Plano, Addison

import type { StationWorldModel } from "./types";

const now = () => new Date();
const minsAgo = (m: number) => new Date(Date.now() - m * 60 * 1000);

export const INITIAL_STATIONS: StationWorldModel[] = [
  // ─── Station 1: Mockingbird ───────────────────────────────────────────────
  {
    id: "mockingbird",
    name: "Mockingbird Station",
    shortName: "Mockingbird",
    line: "Red / Blue Line",
    lineIds: ["red", "blue"],
    city: "Dallas (HP/UP border)",
    politicalStatus: "voting",
    politicalNote: "Highland Park & University Park vote May 2, 2026",
    coordinates: { lat: 32.8367, lng: -96.7719 },
    readinessScore: 71,
    readinessLevel: "fair",
    lastUpdated: now(),
    weather: { tempF: 68, condition: "Partly Cloudy", windMph: 11, humidity: 52 },
    ridership: { today: 3840, peak: 612, trend: "up", peakHour: "8:15 AM" },
    agents: {
      safety: {
        name: "safety", label: "Safety & Security", status: "alert",
        score: 62, weight: 0.25, activeIssues: 2,
        lastAction: "Notified DART PD — 2 encampments flagged at NW platform",
        lastActionTime: minsAgo(14),
        activeAction: { description: "PD unit en route to NW platform", etaMinutes: 12, startedAt: minsAgo(14) },
        incidentsToday: 3, homelessFlags: 2, responseTimeMin: 8.4,
        pdAlertsSent: 2, camerasCoverage: 87,
      },
      cleanliness: {
        name: "cleanliness", label: "Cleanliness", status: "active",
        score: 74, weight: 0.20, activeIssues: 1,
        lastAction: "Crew dispatched — bin #3 at 88%, platform B needs sweep",
        lastActionTime: minsAgo(7),
        activeAction: { description: "Crew en route — Platform B sweep", etaMinutes: 18, startedAt: minsAgo(7) },
        bins: [
          { id: "bin-1", location: "North Entrance", fillLevel: 42, lastEmptied: minsAgo(120) },
          { id: "bin-2", location: "Platform A", fillLevel: 61, lastEmptied: minsAgo(90) },
          { id: "bin-3", location: "Platform B", fillLevel: 88, lastEmptied: minsAgo(210) },
          { id: "bin-4", location: "South Entrance", fillLevel: 35, lastEmptied: minsAgo(80) },
        ],
        crewsDispatched: 2, platformGrade: "B", cleaningsToday: 4,
      },
      equipment: {
        name: "equipment", label: "Equipment", status: "alert",
        score: 71, weight: 0.20, activeIssues: 1,
        lastAction: "PM scheduled Tue 8AM — Elevator A vibration index 74",
        lastActionTime: minsAgo(32),
        activeAction: { description: "Preventive maintenance scheduled — Elevator A", etaMinutes: 2880, startedAt: minsAgo(32) },
        elevators: [
          { id: "elev-a", name: "Elevator A (North)", operational: true, vibrationIndex: 74, lastMaintained: new Date("2026-01-15") },
          { id: "elev-b", name: "Elevator B (South)", operational: true, vibrationIndex: 22, lastMaintained: new Date("2026-02-20") },
        ],
        escalatorsUp: 3, escalatorsTotal: 4, ticketsOpen: 2,
        predictedFailures: [
          { equipmentId: "elev-a", equipmentName: "Elevator A", probability: 78, estimatedHours: 48, severity: "high" },
        ],
      },
      revenue: {
        name: "revenue", label: "Revenue", status: "nominal",
        score: 79, weight: 0.15, activeIssues: 0,
        lastAction: "Peak pricing active — $2.50/hr parking through 9AM",
        lastActionTime: minsAgo(45),
        dailyRevenue: 2840, dailyTarget: 3100, parkingRevenue: 1200,
        adRevenue: 940, retailRevenue: 700, pricingAdjustments: 2,
      },
      parking: {
        name: "parking", label: "Parking", status: "active",
        score: 73, weight: 0.10, activeIssues: 1,
        lastAction: "Issued 3 violations — Zone B overnight vehicles",
        lastActionTime: minsAgo(22),
        zones: [
          { id: "zone-a", name: "Zone A (P&R)", capacity: 180, occupied: 142, evChargers: 6, evInUse: 4, pricePerHour: 2.50 },
          { id: "zone-b", name: "Zone B (Daily)", capacity: 80, occupied: 67, evChargers: 2, evInUse: 1, pricePerHour: 3.00 },
        ],
        totalCapacity: 260, totalOccupied: 209, occupancyRate: 80,
        violationsIssued: 3, parkAndRide: true,
      },
      community: {
        name: "community", label: "Community", status: "nominal",
        score: 81, weight: 0.10, activeIssues: 0,
        lastAction: "Pushed photo spot alert — Golden hour 7:48AM SMU skyline",
        lastActionTime: minsAgo(18),
        photosShared: 7, appRating: 3.9, postsToday: 12,
        activePhotoSpot: "North platform — SMU tower view", riderSentiment: 71,
      },
    },
    events: [
      { id: "mock-e1", agentName: "safety", severity: "critical", title: "Encampment flagged", detail: "2 individuals — NW corner platform. PD notified.", timestamp: minsAgo(14), resolved: false, etaMinutes: 12 },
      { id: "mock-e2", agentName: "equipment", severity: "warning", title: "Elevator A anomaly", detail: "Vibration index 74 — predicted failure in 48hrs. PM scheduled.", timestamp: minsAgo(32), resolved: false, etaMinutes: 2880 },
      { id: "mock-e3", agentName: "cleanliness", severity: "warning", title: "Bin #3 near capacity", detail: "88% full at Platform B. Crew dispatched.", timestamp: minsAgo(7), resolved: false, etaMinutes: 18 },
      { id: "mock-e4", agentName: "parking", severity: "info", title: "Violations issued", detail: "3 overnight vehicles in Zone B. Citations logged.", timestamp: minsAgo(22), resolved: true, resolvedAt: minsAgo(10) },
      { id: "mock-e5", agentName: "community", severity: "info", title: "Photo spot activated", detail: "Golden hour alert sent to 340 riders nearby.", timestamp: minsAgo(18), resolved: true, resolvedAt: minsAgo(18) },
    ],
    cityRoi: { taxContributed: 48200, serviceValueReceived: 41800, roiRatio: 0.87 },
  },

  // ─── Station 2: Downtown Plano ────────────────────────────────────────────
  {
    id: "downtown-plano",
    name: "Downtown Plano Station",
    shortName: "Downtown Plano",
    line: "Red Line",
    lineIds: ["red"],
    city: "Plano",
    politicalStatus: "stable",
    politicalNote: "Plano rescinded withdrawal — Feb 2026 Grand Compromise",
    coordinates: { lat: 33.0198, lng: -96.6989 },
    readinessScore: 89,
    readinessLevel: "good",
    lastUpdated: now(),
    weather: { tempF: 67, condition: "Clear", windMph: 8, humidity: 48 },
    ridership: { today: 4210, peak: 688, trend: "up", peakHour: "8:05 AM" },
    agents: {
      safety: {
        name: "safety", label: "Safety & Security", status: "nominal",
        score: 94, weight: 0.25, activeIssues: 0,
        lastAction: "Scheduled patrol confirmed — all cameras nominal",
        lastActionTime: minsAgo(5),
        incidentsToday: 0, homelessFlags: 0, responseTimeMin: 3.2,
        pdAlertsSent: 0, camerasCoverage: 96,
      },
      cleanliness: {
        name: "cleanliness", label: "Cleanliness", status: "nominal",
        score: 92, weight: 0.20, activeIssues: 0,
        lastAction: "Morning sweep complete — all bins under 60%",
        lastActionTime: minsAgo(28),
        bins: [
          { id: "bin-1", location: "North Entrance", fillLevel: 28, lastEmptied: minsAgo(30) },
          { id: "bin-2", location: "Platform A", fillLevel: 41, lastEmptied: minsAgo(28) },
          { id: "bin-3", location: "Platform B", fillLevel: 33, lastEmptied: minsAgo(30) },
          { id: "bin-4", location: "Parking Entry", fillLevel: 19, lastEmptied: minsAgo(45) },
        ],
        crewsDispatched: 0, platformGrade: "A", cleaningsToday: 6,
      },
      equipment: {
        name: "equipment", label: "Equipment", status: "nominal",
        score: 91, weight: 0.20, activeIssues: 0,
        lastAction: "All elevators nominal — next PM in 14 days",
        lastActionTime: minsAgo(60),
        elevators: [
          { id: "elev-a", name: "Elevator A (North)", operational: true, vibrationIndex: 18, lastMaintained: new Date("2026-02-28") },
          { id: "elev-b", name: "Elevator B (South)", operational: true, vibrationIndex: 12, lastMaintained: new Date("2026-03-01") },
        ],
        escalatorsUp: 4, escalatorsTotal: 4, ticketsOpen: 0,
        predictedFailures: [],
      },
      revenue: {
        name: "revenue", label: "Revenue", status: "nominal",
        score: 88, weight: 0.15, activeIssues: 0,
        lastAction: "Dynamic pricing optimized — $1.50/hr, 91% P&R fill",
        lastActionTime: minsAgo(55),
        dailyRevenue: 4210, dailyTarget: 4000, parkingRevenue: 2100,
        adRevenue: 1300, retailRevenue: 810, pricingAdjustments: 1,
      },
      parking: {
        name: "parking", label: "Parking", status: "nominal",
        score: 89, weight: 0.10, activeIssues: 0,
        lastAction: "EV chargers all operational — Zone A 91% occupied",
        lastActionTime: minsAgo(40),
        zones: [
          { id: "zone-a", name: "Zone A (P&R)", capacity: 320, occupied: 291, evChargers: 12, evInUse: 9, pricePerHour: 1.50 },
          { id: "zone-b", name: "Zone B (Hourly)", capacity: 120, occupied: 88, evChargers: 4, evInUse: 2, pricePerHour: 2.00 },
        ],
        totalCapacity: 440, totalOccupied: 379, occupancyRate: 86,
        violationsIssued: 0, parkAndRide: true,
      },
      community: {
        name: "community", label: "Community", status: "nominal",
        score: 87, weight: 0.10, activeIssues: 0,
        lastAction: "Historic downtown mural post — 31 shares, trending",
        lastActionTime: minsAgo(35),
        photosShared: 31, appRating: 4.7, postsToday: 18,
        activePhotoSpot: "Heritage building backdrop — east platform", riderSentiment: 89,
      },
    },
    events: [
      { id: "plano-e1", agentName: "revenue", severity: "info", title: "Revenue target exceeded", detail: "$4,210 — 105% of daily target by noon.", timestamp: minsAgo(55), resolved: true, resolvedAt: minsAgo(55) },
      { id: "plano-e2", agentName: "community", severity: "info", title: "Viral photo post", detail: "Mural shot shared 31 times on social — 1.2K reach.", timestamp: minsAgo(35), resolved: true, resolvedAt: minsAgo(35) },
      { id: "plano-e3", agentName: "cleanliness", severity: "info", title: "Morning sweep done", detail: "All 4 bins under 45%. Platform grade: A.", timestamp: minsAgo(28), resolved: true, resolvedAt: minsAgo(28) },
      { id: "plano-e4", agentName: "parking", severity: "info", title: "P&R near capacity", detail: "Zone A at 91% — early commuters arriving.", timestamp: minsAgo(40), resolved: true, resolvedAt: minsAgo(40) },
    ],
    cityRoi: { taxContributed: 110000, serviceValueReceived: 138000, roiRatio: 1.25 },
  },

  // ─── Station 3: Addison (Silver Line) ─────────────────────────────────────
  {
    id: "addison",
    name: "Addison Station",
    shortName: "Addison",
    line: "Silver Line (new)",
    lineIds: ["silver"],
    city: "Addison",
    politicalStatus: "voting",
    politicalNote: "Addison proceeding to vote — May 2, 2026. This station at stake.",
    coordinates: { lat: 32.9612, lng: -96.8283 },
    readinessScore: 63,
    readinessLevel: "at-risk",
    lastUpdated: now(),
    weather: { tempF: 69, condition: "Clear", windMph: 14, humidity: 45 },
    ridership: { today: 1620, peak: 241, trend: "up", peakHour: "8:30 AM" },
    agents: {
      safety: {
        name: "safety", label: "Safety & Security", status: "critical",
        score: 55, weight: 0.25, activeIssues: 3,
        lastAction: "ESCALATED — lighting outage zone C, 1 incident reported",
        lastActionTime: minsAgo(8),
        activeAction: { description: "Electrician + PD dispatched to Zone C", etaMinutes: 25, startedAt: minsAgo(8) },
        incidentsToday: 4, homelessFlags: 3, responseTimeMin: 18.7,
        pdAlertsSent: 3, camerasCoverage: 64,
      },
      cleanliness: {
        name: "cleanliness", label: "Cleanliness", status: "alert",
        score: 58, weight: 0.20, activeIssues: 2,
        lastAction: "Construction debris on platform C — crew en route",
        lastActionTime: minsAgo(11),
        activeAction: { description: "Crew clearing Platform C debris", etaMinutes: 30, startedAt: minsAgo(11) },
        bins: [
          { id: "bin-1", location: "Main Entrance", fillLevel: 91, lastEmptied: minsAgo(480) },
          { id: "bin-2", location: "Platform A", fillLevel: 74, lastEmptied: minsAgo(240) },
          { id: "bin-3", location: "Platform B", fillLevel: 62, lastEmptied: minsAgo(180) },
          { id: "bin-4", location: "Parking Entry", fillLevel: 55, lastEmptied: minsAgo(120) },
        ],
        crewsDispatched: 1, platformGrade: "C", cleaningsToday: 2,
      },
      equipment: {
        name: "equipment", label: "Equipment", status: "alert",
        score: 61, weight: 0.20, activeIssues: 2,
        lastAction: "Lighting zone C failed — electrician dispatched",
        lastActionTime: minsAgo(8),
        activeAction: { description: "Elevator A repair + Zone C lighting restore", etaMinutes: 4320, startedAt: minsAgo(120) },
        elevators: [
          { id: "elev-a", name: "Elevator A", operational: false, vibrationIndex: 0, lastMaintained: new Date("2026-01-10") },
          { id: "elev-b", name: "Elevator B", operational: true, vibrationIndex: 31, lastMaintained: new Date("2026-02-15") },
        ],
        escalatorsUp: 2, escalatorsTotal: 4, ticketsOpen: 4,
        predictedFailures: [
          { equipmentId: "elev-a", equipmentName: "Elevator A", probability: 100, estimatedHours: 0, severity: "high" },
          { equipmentId: "esc-c", equipmentName: "Escalator C", probability: 65, estimatedHours: 24, severity: "medium" },
        ],
      },
      revenue: {
        name: "revenue", label: "Revenue", status: "alert",
        score: 61, weight: 0.15, activeIssues: 1,
        lastAction: "Adjusted pricing -20% — low occupancy, off-peak",
        lastActionTime: minsAgo(62),
        dailyRevenue: 810, dailyTarget: 1800, parkingRevenue: 380,
        adRevenue: 290, retailRevenue: 140, pricingAdjustments: 3,
      },
      parking: {
        name: "parking", label: "Parking", status: "alert",
        score: 64, weight: 0.10, activeIssues: 1,
        lastAction: "Construction blocks 40 spaces — advisory sent to riders",
        lastActionTime: minsAgo(90),
        zones: [
          { id: "zone-a", name: "Zone A (P&R)", capacity: 200, occupied: 71, evChargers: 8, evInUse: 2, pricePerHour: 1.00 },
          { id: "zone-b", name: "Zone B (Temp)", capacity: 60, occupied: 28, evChargers: 0, evInUse: 0, pricePerHour: 0.75 },
        ],
        totalCapacity: 260, totalOccupied: 99, occupancyRate: 38,
        violationsIssued: 1, parkAndRide: true,
      },
      community: {
        name: "community", label: "Community", status: "nominal",
        score: 72, weight: 0.10, activeIssues: 0,
        lastAction: "Silver Line launch highlights — 4 shares today",
        lastActionTime: minsAgo(44),
        photosShared: 4, appRating: 3.1, postsToday: 6,
        activePhotoSpot: "Silver Line inaugural train — Platform A", riderSentiment: 58,
      },
    },
    events: [
      { id: "add-e1", agentName: "safety", severity: "critical", title: "Lighting failure + incident", detail: "Zone C dark — 1 incident reported. Electrician + PD dispatched.", timestamp: minsAgo(8), resolved: false, etaMinutes: 25 },
      { id: "add-e2", agentName: "safety", severity: "critical", title: "3 homeless encampments", detail: "North tunnel area. DART social services + PD notified.", timestamp: minsAgo(45), resolved: false, etaMinutes: 60 },
      { id: "add-e3", agentName: "equipment", severity: "critical", title: "Elevator A offline", detail: "Out of service. ADA notice published. Repair ETA: 72hrs.", timestamp: minsAgo(120), resolved: false, etaMinutes: 4320 },
      { id: "add-e4", agentName: "cleanliness", severity: "warning", title: "Bin #1 overflow risk", detail: "91% — construction crews not disposing properly.", timestamp: minsAgo(11), resolved: false, etaMinutes: 30 },
      { id: "add-e5", agentName: "revenue", severity: "warning", title: "Revenue 45% of target", detail: "$810 vs $1,800 target. Construction reducing access.", timestamp: minsAgo(62), resolved: false, etaMinutes: 480 },
    ],
    cityRoi: { taxContributed: 32000, serviceValueReceived: 18500, roiRatio: 0.58 },
  },
];
