// ─── KAI Mobile App Mock Data ─────────────────────────────────────────────────
import type { AppStation, Incident, WorkOrder, Task, Alert, City, KPI } from './types'

export const CITY: City = {
  id: 'dallas',
  name: 'Dallas',
  state: 'TX',
  score: 87,
  stations: 65,
  activeIncidents: 12,
  openWorkOrders: 34,
  trend: 'up',
  lastUpdated: new Date().toISOString(),
}

export const CITY_KPIS: KPI[] = [
  { label: 'Network readiness', value: 87, unit: '%', trend: 'up', trendValue: '+3 pts', positiveDirection: 'up' },
  { label: 'Active incidents', value: 12, trend: 'down', trendValue: '−4 today', positiveDirection: 'down' },
  { label: 'Open work orders', value: 34, trend: 'stable', trendValue: 'No change', positiveDirection: 'down' },
  { label: 'Avg response time', value: '8.4', unit: 'min', trend: 'down', trendValue: '−1.2 min', positiveDirection: 'down' },
]

export const STATIONS: AppStation[] = [
  {
    id: 'union',
    name: 'Union Station',
    shortName: 'UNION',
    line: 'Red / Blue',
    lineColor: '#DC2626',
    score: 94,
    status: 'nominal',
    safetyScore: 96,
    cleanlinessScore: 92,
    maintenanceScore: 94,
    activeIncidents: 0,
    openWorkOrders: 2,
    location: 'Downtown Dallas',
    lastInspected: '2h ago',
    lat: 32.7767,
    lng: -96.797,
  },
  {
    id: 'akard',
    name: 'Akard Station',
    shortName: 'AKARD',
    line: 'Red / Blue',
    lineColor: '#DC2626',
    score: 78,
    status: 'degraded',
    safetyScore: 80,
    cleanlinessScore: 72,
    maintenanceScore: 82,
    activeIncidents: 2,
    openWorkOrders: 5,
    location: 'Downtown Dallas',
    lastInspected: '45m ago',
    lat: 32.7801,
    lng: -96.799,
  },
  {
    id: 'victory',
    name: 'Victory Station',
    shortName: 'VCTRY',
    line: 'Green / Orange',
    lineColor: '#16A34A',
    score: 91,
    status: 'nominal',
    safetyScore: 93,
    cleanlinessScore: 90,
    maintenanceScore: 90,
    activeIncidents: 0,
    openWorkOrders: 1,
    location: 'Victory Park',
    lastInspected: '1h ago',
    lat: 32.787,
    lng: -96.808,
  },
  {
    id: 'west-transfer',
    name: 'West Transfer Center',
    shortName: 'WEST-TC',
    line: 'Red / Blue',
    lineColor: '#DC2626',
    score: 62,
    status: 'critical',
    safetyScore: 58,
    cleanlinessScore: 60,
    maintenanceScore: 68,
    activeIncidents: 4,
    openWorkOrders: 9,
    location: 'West Dallas',
    lastInspected: '3h ago',
    lat: 32.774,
    lng: -96.843,
  },
  {
    id: 'mockingbird',
    name: 'Mockingbird Station',
    shortName: 'MOCK',
    line: 'Red / Blue',
    lineColor: '#DC2626',
    score: 88,
    status: 'nominal',
    safetyScore: 90,
    cleanlinessScore: 86,
    maintenanceScore: 88,
    activeIncidents: 1,
    openWorkOrders: 3,
    location: 'East Dallas',
    lastInspected: '30m ago',
    lat: 32.836,
    lng: -96.778,
  },
  {
    id: 'cityplace',
    name: 'CityPlace / Uptown',
    shortName: 'CITYP',
    line: 'Red / Blue',
    lineColor: '#DC2626',
    score: 84,
    status: 'nominal',
    safetyScore: 85,
    cleanlinessScore: 84,
    maintenanceScore: 83,
    activeIncidents: 1,
    openWorkOrders: 2,
    location: 'Uptown Dallas',
    lastInspected: '1.5h ago',
    lat: 32.796,
    lng: -96.797,
  },
  {
    id: 'cedars',
    name: 'Cedars Station',
    shortName: 'CDRS',
    line: 'Red / Blue',
    lineColor: '#DC2626',
    score: 72,
    status: 'degraded',
    safetyScore: 70,
    cleanlinessScore: 68,
    maintenanceScore: 78,
    activeIncidents: 3,
    openWorkOrders: 6,
    location: 'South Dallas',
    lastInspected: '2.5h ago',
    lat: 32.765,
    lng: -96.793,
  },
  {
    id: 'downtown-garland',
    name: 'Downtown Garland',
    shortName: 'D-GRLN',
    line: 'Blue',
    lineColor: '#2563EB',
    score: 95,
    status: 'nominal',
    safetyScore: 96,
    cleanlinessScore: 95,
    maintenanceScore: 94,
    activeIncidents: 0,
    openWorkOrders: 1,
    location: 'Garland',
    lastInspected: '20m ago',
    lat: 32.9126,
    lng: -96.634,
  },
  {
    id: 'farmers-branch',
    name: 'Farmers Branch',
    shortName: 'F-BRNCH',
    line: 'Green',
    lineColor: '#16A34A',
    score: 89,
    status: 'nominal',
    safetyScore: 91,
    cleanlinessScore: 88,
    maintenanceScore: 88,
    activeIncidents: 0,
    openWorkOrders: 2,
    location: 'Farmers Branch',
    lastInspected: '1h ago',
    lat: 32.926,
    lng: -96.899,
  },
  {
    id: 'buckner',
    name: 'Buckner Station',
    shortName: 'BKNER',
    line: 'Blue',
    lineColor: '#2563EB',
    score: 75,
    status: 'degraded',
    safetyScore: 74,
    cleanlinessScore: 76,
    maintenanceScore: 75,
    activeIncidents: 2,
    openWorkOrders: 4,
    location: 'East Dallas',
    lastInspected: '4h ago',
    lat: 32.786,
    lng: -96.699,
  },
]

export const INCIDENTS: Incident[] = [
  {
    id: 'inc-001',
    title: 'Elevator out of service — West Transfer Center',
    description: 'Elevator #2 on Platform B is non-operational. ADA compliance at risk. Estimated repair: 4 hours.',
    priority: 'critical',
    status: 'in_progress',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    category: 'equipment',
    reportedBy: 'Marcus R.',
    assignedTo: 'Field Crew A',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    notes: ['Parts ordered', 'Tech on-site at 09:45'],
  },
  {
    id: 'inc-002',
    title: 'Graffiti on southbound platform wall',
    description: 'Large graffiti tag on the southbound platform wall at Akard. Visible from street level.',
    priority: 'medium',
    status: 'open',
    stationId: 'akard',
    stationName: 'Akard Station',
    category: 'sanitation',
    reportedBy: 'Auto-detection',
    assignedTo: undefined,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    notes: [],
  },
  {
    id: 'inc-003',
    title: 'Homeless encampment — Cedars Platform C',
    description: 'Four individuals with belongings blocking Platform C entry. Safety concern for passengers.',
    priority: 'high',
    status: 'in_progress',
    stationId: 'cedars',
    stationName: 'Cedars Station',
    category: 'safety',
    reportedBy: 'Station Officer L.',
    assignedTo: 'Safety Team B',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    notes: ['PD notified', 'Outreach coordinator en route'],
  },
  {
    id: 'inc-004',
    title: 'Broken ticket validator — Mockingbird',
    description: 'Validator unit #3 on concourse is rejecting all cards. Revenue impact ~$240/hr.',
    priority: 'high',
    status: 'open',
    stationId: 'mockingbird',
    stationName: 'Mockingbird Station',
    category: 'equipment',
    reportedBy: 'Revenue Agent',
    assignedTo: undefined,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    notes: [],
  },
  {
    id: 'inc-005',
    title: 'Spill on stairwell — West Transfer Center',
    description: 'Liquid spill on main stairwell. Slip hazard. Crew needed immediately.',
    priority: 'critical',
    status: 'in_progress',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    category: 'safety',
    reportedBy: 'Passenger Report',
    assignedTo: 'Cleaning Crew 3',
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    notes: ['Hazard cone placed', 'Crew ETA 5 min'],
  },
  {
    id: 'inc-006',
    title: 'Lighting failure — CityPlace concourse',
    description: 'Six overhead lights out on the north concourse. Reducing visibility during off-peak hours.',
    priority: 'medium',
    status: 'open',
    stationId: 'cityplace',
    stationName: 'CityPlace / Uptown',
    category: 'equipment',
    reportedBy: 'Night Inspector',
    assignedTo: undefined,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    notes: [],
  },
  {
    id: 'inc-007',
    title: 'Excessive bin fill — Cedars all platforms',
    description: 'All bins at Cedars above 90% capacity. Overflow risk. Cleanliness score dropped to 68.',
    priority: 'medium',
    status: 'open',
    stationId: 'cedars',
    stationName: 'Cedars Station',
    category: 'sanitation',
    reportedBy: 'Bin Sensor Network',
    assignedTo: undefined,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    notes: [],
  },
  {
    id: 'inc-008',
    title: 'Structural crack — Buckner platform wall',
    description: 'Hairline structural crack detected on east platform retaining wall. Engineering assessment needed.',
    priority: 'high',
    status: 'open',
    stationId: 'buckner',
    stationName: 'Buckner Station',
    category: 'structural',
    reportedBy: 'Inspection Team',
    assignedTo: undefined,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    notes: ['Engineering ticket opened'],
  },
]

export const WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-001',
    title: 'Replace elevator #2 motor assembly — West Transfer',
    description: 'Motor assembly on Elevator #2 Platform B requires full replacement. Parts on order.',
    priority: 'critical',
    status: 'in_progress',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    category: 'corrective',
    assignedTo: 'James L.',
    assignedTeam: 'Mechanical Team A',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 6,
    notes: ['Parts arrived at 10:30', 'Tech began at 11:00'],
  },
  {
    id: 'wo-002',
    title: 'Quarterly elevator maintenance — Union Station',
    description: 'Scheduled quarterly preventive maintenance for all 4 elevators.',
    priority: 'low',
    status: 'assigned',
    stationId: 'union',
    stationName: 'Union Station',
    category: 'preventive',
    assignedTo: 'Sarah K.',
    assignedTeam: 'Mechanical Team B',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 8,
    notes: [],
  },
  {
    id: 'wo-003',
    title: 'Replace validator unit #3 — Mockingbird',
    description: 'Ticket validator #3 failed hardware check. Replacement unit in stock.',
    priority: 'high',
    status: 'pending',
    stationId: 'mockingbird',
    stationName: 'Mockingbird Station',
    category: 'corrective',
    assignedTo: undefined,
    assignedTeam: 'Revenue Tech Team',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 2,
    notes: [],
  },
  {
    id: 'wo-004',
    title: 'Graffiti removal — Akard south platform',
    description: 'Chemical graffiti removal on south platform wall. 12 sq ft area.',
    priority: 'medium',
    status: 'pending',
    stationId: 'akard',
    stationName: 'Akard Station',
    category: 'corrective',
    assignedTo: undefined,
    assignedTeam: 'Cleaning Crew 2',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 3,
    notes: [],
  },
  {
    id: 'wo-005',
    title: 'Replace 6 overhead lights — CityPlace concourse',
    description: 'LED replacement for failed overhead fixtures on north concourse.',
    priority: 'medium',
    status: 'assigned',
    stationId: 'cityplace',
    stationName: 'CityPlace / Uptown',
    category: 'corrective',
    assignedTo: 'Tom B.',
    assignedTeam: 'Electrical Team',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 2,
    notes: ['Fixtures on order — arriving tomorrow'],
  },
  {
    id: 'wo-006',
    title: 'Structural assessment — Buckner east wall',
    description: 'Engineering inspection and assessment of hairline crack. Report required within 48h.',
    priority: 'high',
    status: 'pending',
    stationId: 'buckner',
    stationName: 'Buckner Station',
    category: 'inspection',
    assignedTo: undefined,
    assignedTeam: 'Structural Engineering',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 40 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 4,
    notes: [],
  },
  {
    id: 'wo-007',
    title: 'Deep clean all bins — Cedars Station',
    description: 'Empty, clean, and sanitize all 18 waste bins across all Cedars platforms.',
    priority: 'medium',
    status: 'in_progress',
    stationId: 'cedars',
    stationName: 'Cedars Station',
    category: 'corrective',
    assignedTo: 'Maria G.',
    assignedTeam: 'Sanitation Team C',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    estimatedHours: 2,
    notes: ['12 of 18 bins completed'],
  },
  {
    id: 'wo-008',
    title: 'Monthly safety inspection — Victory Station',
    description: 'Monthly full-station safety walkthrough and report.',
    priority: 'low',
    status: 'completed',
    stationId: 'victory',
    stationName: 'Victory Station',
    category: 'inspection',
    assignedTo: 'David P.',
    assignedTeam: 'Safety Team A',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 3,
    actualHours: 2.5,
    notes: ['All items passed. Minor suggestion filed for handrail tightening.'],
  },
]

export const TASKS: Task[] = [
  {
    id: 'task-001',
    title: 'Confirm elevator parts delivery — West Transfer',
    description: 'Verify parts arrived and sign off on delivery receipt. Log in system.',
    priority: 'critical',
    status: 'done',
    assignedTo: 'James L.',
    workOrderId: 'wo-001',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    dueAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    photoRequired: true,
    notes: 'Parts confirmed. Photo attached.',
  },
  {
    id: 'task-002',
    title: 'Install elevator motor assembly — West Transfer',
    description: 'Full motor replacement on Elevator #2 Platform B. Follow SOP-ELEV-04.',
    priority: 'critical',
    status: 'in_progress',
    assignedTo: 'James L.',
    workOrderId: 'wo-001',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    dueAt: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    photoRequired: true,
  },
  {
    id: 'task-003',
    title: 'Post-install elevator test — West Transfer',
    description: 'Run 10-cycle test on Elevator #2 after motor replacement. Document results.',
    priority: 'critical',
    status: 'todo',
    assignedTo: 'James L.',
    workOrderId: 'wo-001',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    dueAt: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    photoRequired: false,
  },
  {
    id: 'task-004',
    title: 'Replace validator unit #3 — Mockingbird',
    description: 'Swap out failed validator unit. Test with 5 card types before closing.',
    priority: 'high',
    status: 'todo',
    assignedTo: 'Unassigned',
    workOrderId: 'wo-003',
    stationId: 'mockingbird',
    stationName: 'Mockingbird Station',
    dueAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    photoRequired: true,
  },
  {
    id: 'task-005',
    title: 'Empty bins at Cedars — Platforms A and B',
    description: 'Empty and clean 6 bins on Platform A and 4 on Platform B.',
    priority: 'medium',
    status: 'in_progress',
    assignedTo: 'Maria G.',
    workOrderId: 'wo-007',
    stationId: 'cedars',
    stationName: 'Cedars Station',
    dueAt: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    photoRequired: false,
  },
  {
    id: 'task-006',
    title: 'Place hazard cones — West Transfer stairwell',
    description: 'Place 4 hazard cones around liquid spill on main stairwell until crew arrives.',
    priority: 'critical',
    status: 'done',
    assignedTo: 'Station Officer D.',
    incidentId: 'inc-005',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    dueAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    photoRequired: false,
    notes: 'Cones placed. Area sealed.',
  },
  {
    id: 'task-007',
    title: 'Clean spill — West Transfer main stairwell',
    description: 'Full biohazard clean on stairwell. Dry thoroughly. Remove cones when safe.',
    priority: 'critical',
    status: 'in_progress',
    assignedTo: 'Cleaning Crew 3',
    incidentId: 'inc-005',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    dueAt: new Date(Date.now() + 20 * 60 * 1000).toISOString(),
    photoRequired: true,
  },
  {
    id: 'task-008',
    title: 'Conduct PD welfare check — Cedars Platform C',
    description: 'Coordinate with Dallas PD for welfare check on individuals at Platform C.',
    priority: 'high',
    status: 'in_progress',
    assignedTo: 'Safety Team B',
    incidentId: 'inc-003',
    stationId: 'cedars',
    stationName: 'Cedars Station',
    dueAt: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    photoRequired: false,
  },
]

export const ALERTS: Alert[] = [
  {
    id: 'alert-001',
    title: 'ADA compliance risk',
    message: 'Elevator #2 at West Transfer Center has been offline for 2+ hours. ADA compliance now at risk.',
    severity: 'critical',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    category: 'Equipment',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledgedBy: 'James L.',
  },
  {
    id: 'alert-002',
    title: 'Slip hazard — active',
    message: 'Uncontrolled spill on West Transfer main stairwell. Crew dispatched.',
    severity: 'critical',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    category: 'Safety',
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledgedBy: 'Dispatch',
  },
  {
    id: 'alert-003',
    title: 'Safety score below threshold',
    message: 'West Transfer Center safety score fell to 58 — below the 65-point threshold.',
    severity: 'critical',
    stationId: 'west-transfer',
    stationName: 'West Transfer Center',
    category: 'Score',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'alert-004',
    title: 'High platform congestion',
    message: 'Buckner Station Platform B occupancy at 94%. Monitor for crowd control.',
    severity: 'warning',
    stationId: 'buckner',
    stationName: 'Buckner Station',
    category: 'Capacity',
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'alert-005',
    title: 'Bin overflow risk',
    message: 'All bins at Cedars Station above 90% fill level. Crew has been dispatched.',
    severity: 'warning',
    stationId: 'cedars',
    stationName: 'Cedars Station',
    category: 'Sanitation',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledgedBy: 'Dispatch',
  },
  {
    id: 'alert-006',
    title: 'Revenue loss — validator offline',
    message: 'Mockingbird validator #3 offline. Estimated revenue loss: $240/hr.',
    severity: 'warning',
    stationId: 'mockingbird',
    stationName: 'Mockingbird Station',
    category: 'Revenue',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'alert-007',
    title: 'Structural defect logged',
    message: 'Hairline crack detected at Buckner east platform wall. Engineering assessment scheduled.',
    severity: 'warning',
    stationId: 'buckner',
    stationName: 'Buckner Station',
    category: 'Structural',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledgedBy: 'Chief Engineer',
  },
  {
    id: 'alert-008',
    title: 'Scheduled maintenance reminder',
    message: 'Union Station quarterly elevator maintenance is due in 48 hours.',
    severity: 'info',
    stationId: 'union',
    stationName: 'Union Station',
    category: 'Maintenance',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledgedBy: 'Ops Manager',
  },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────
export function getStation(id: string): AppStation | undefined {
  return STATIONS.find(s => s.id === id)
}

export function getIncident(id: string): Incident | undefined {
  return INCIDENTS.find(i => i.id === id)
}

export function getWorkOrder(id: string): WorkOrder | undefined {
  return WORK_ORDERS.find(wo => wo.id === id)
}

export function getTask(id: string): Task | undefined {
  return TASKS.find(t => t.id === id)
}

export function formatRelativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 1) return 'Just now'
  if (mins < 60) return `${mins}m ago`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return `${hrs}h ago`
  return `${Math.floor(hrs / 24)}d ago`
}

export function formatDueTime(iso: string): string {
  const diff = new Date(iso).getTime() - Date.now()
  const mins = Math.floor(Math.abs(diff) / 60000)
  const past = diff < 0
  if (mins < 60) return past ? `${mins}m overdue` : `in ${mins}m`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return past ? `${hrs}h overdue` : `in ${hrs}h`
  return past ? `${Math.floor(hrs / 24)}d overdue` : `in ${Math.floor(hrs / 24)}d`
}
